org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=GatewaysToEternity
modName=Gateways To Eternity
modGroup=dev.shadowsoffire
modid=gateways
author=Shadows_of_Fire
desc=Adds combat-based events which provide various rewards and challenges.
version=5.0.3

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.144
parchmentVersion=2024.07.28-1.21
jeiVersion=19.8.4.113
jadeVersion=15.1.6
placeboVersion=9.8.0
#patchouliVersion=1.19.2-76
attributeslibVersion=2.7.0
#crafttweakerVersion=14.0.12
#crafttweakerAPVersion=3.0.0.15

# Mixins
mixin=true
mixinVersion=0.8.5

# Publishing
requiredDeps=placebo, apothic-attributes
#optionalDeps=
#incompatibleDeps=
releaseType=beta
modLoaders=NeoForge
curseforgeProjectId=417802

# Tests
enableTests=false
