org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=GatewaysToEternity
modName=Gateways To Eternity
modGroup=dev.shadowsoffire
modid=gateways
author=Shadows_of_Fire
desc=Adds combat-based events which provide various rewards and challenges.
version=5.1.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.187
parchmentVersion=2024.11.17-1.21.1
jeiVersion=19.21.2.313
jadeVersion=15.10.2
placeboVersion=9.9.1
attributeslibVersion=2.7.0

# Mixins
mixin=true
mixinVersion=0.8.5

# Publishing
requiredDeps=placebo, apothic-attributes
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=417802

# Tests
enableTests=false
