org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=GatewaysToEternity
modName=Gateways To Eternity
modGroup=dev.shadowsoffire
modid=gateways
author=Shadows_of_Fire
desc=Adds combat-based events which provide various rewards and challenges.
version=6.0.0-beta2

# Dependencies
mcVersion=26.1.2
javaVersion=25
forgeVersion=26.1.2.22-beta
jeiVersion=29.5.0.26
jadeVersion=26.0.9
placeboVersion=10.0.0-beta8
attributeslibVersion=3.0.0-beta0

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
requiredDeps=placebo, apothic-attributes
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=417802

# Tests
enableTests=false
