modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="gateways"

version="6.0.0-beta3"

displayName="Gateways To Eternity"

authors="Shadows_of_Fire"

description='''Adds combat-based events which provide various rewards and challenges.'''

[[mixins]]
config="gateways.mixins.json"

[[dependencies.gateways]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gateways]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.22-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gateways]]
    modId="placebo"
    type="required"
    versionRange="[10.0.0-beta15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gateways]]
    modId="apothic_attributes"
    type="required"
    versionRange="[3.0.0-beta5,)"
    ordering="NONE"
    side="BOTH"
